#TEMPLATE = lib
#CONFIG += c++11 warn_off
#QT -= core gui
#QMAKE_CXXFLAGS += -Wall -Wno-unused-parameter

DEFINES += FT2_BUILD_LIBRARY

unix:!macx {
    DEFINES += _FX_OS_=_FX_LINUX_DESKTOP_
    DEFINES += _FXM_PLATFORM_=_FXM_PLATFORM_LINUX_
}
macx {
    DEFINES += _FX_OS_=_FX_MACOSX_
    DEFINES += _FXM_PLATFORM_=_FXM_PLATFORM_APPLE_
}
win32 {
    DEFINES += _FX_OS_=_FX_WIN32_DESKTOP_
    DEFINES += _FXM_PLATFORM_=_FXM_PLATFORM_WINDOWS_
}
